scene_dict = {
    "chair":{
        "scale_physical2world":0.055,
        "physical_width":78.55,
        "thickness":9.09,
        "vertical":"z",
        "orientation":"xoz"
    },
    "lego_entity":{
        "scale_physical2world":0.07716,
        "physical_width":77.76,
        "thickness":11,
        "ground":-0.5,
        "vertical":"x",
        "orientation":"yox"
    },
    "matrixcity":{
        "scale_physical2world":0.23,
        "thickness":5,
        "vertical":"y",
        "delta_y":1.5,
        "orientation":"xoy"
    },
    "lego_bulldozer":{
        "scale_physical2world":0.083,
        "thickness":6,
        "vertical":"z",
        "ground_coefficient":-0.5,
        "orientation":"yoz"
    },
    "minecraft":{
        "scale_physical2world":2,
        "thickness":74.07,
        "vertical":"y",
        "orientation":"zox"
    },
    "metal_materials":{
        "scale_physical2world":0.025,
        "thickness":12,
        "physical_width":103.68,
        "vertical":"y",
        "orientation":"xoy"
    },
    "wukang_mansion":{
        "scale_physical2world":0.0667,
        "thickness":6,
        "vertical":"z",
        "ground_coefficient":-1,
        "orientation":"yoz"
    },
    "truck":{
        "scale_physical2world":0.083,
        "thickness":6,
        "physical_width":52.05,
        "vertical":"z",
        "ground_coefficient":-0.5,
        "orientation":"yoz"
    },
    "room_floor":{
        "scale_physical2world":0.015,
        "thickness":46.7,
        "physical_width":288,
        "vertical":"z",
        "ground_coefficient":-0.5,
        "delta_y":0.35,
        "delta_z":0.15,
        "orientation":"yoz"
    },
    "desk_bookshelf":{
        "scale_physical2world":0.025,
        "thickness":6,
        "physical_width":172.8,
        "vertical":"z",
        "orientation":"yoz"
    },
    "hotdog":{
        "scale_physical2world":0.06,
        "thickness":10,
        "physical_width":43.2,
        "vertical":"z",
        "orientation":"xoz",
        "ground_coefficient":-0.5,
    },
    "orchids":{
        "scale_physical2world":0.04,
        "thickness":100,
        "physical_width":432,
        "vertical":"z",
        "orientation":"yoz",
        "ground_coefficient":-1.2,
    },
    "china_art_museum":{
        "scale_physical2world":0.03,
        "thickness":25,
        "physical_width":115.2,
        "vertical":"z",
        "orientation":"yoz",
    },
    "traffic":{
        "scale_physical2world":0.04,
        "thickness":8.75,
        "physical_width":108,
        "vertical":"z",
        "orientation":"yoz",
    },
    "ficus":{
        "scale_physical2world":0.05,
        "thickness":10,
        "physical_width":77.76,
        "vertical":"z",
        "orientation":"xoz",
        "ground_coefficient":-0.5,
    },
    "shoe_rack":{
        "scale_physical2world":0.083,
        "thickness":12,
        "physical_width":104.1,
        "vertical":"z",
        "orientation":"yoz",
        "ground_coefficient":-0.5,
    },
    "street":{
        "scale_physical2world":0.02,
        "thickness":100,
        "physical_width":648,
        "vertical":"z",
        "orientation":"yoz",
        "ground":-1,
    },
}